version: '2'

services:
  cli:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    command: '/bin/bash'
    tty: true

  web:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - '8080:3000'
    tty: true
    command: bash -c "bundle install && bundle exec rails s"
