version: '2'

services:
  cli:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    command: '/bin/bash'
    tty: true

  web:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - '8080:3000'
    command: '/opt/bin/rails_s.sh'
    tty: true

  sqlite3-dump:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    command: '/opt/bin/sqlite_dump.sh'
    tty: true

  scrape:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    command: '/opt/bin/rake_get_all_tests.sh'
    tty: true



