version: '2'

services:
  cli:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    command: '/bin/bash'
    tty: true
    ports:
      - '8080:3000'
      - '4444:4444'

  web:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      RAILS_ENV: ${RAILS_ENV}
    ports:
      - '9080:3000'
    command: '/opt/gin/entry_point.sh'
    tty: true
    command: "bundle install && bundle exec rails s"
