version: '2'

services:
  speedy:
    build: ./app
    volumes:
      - .:/var/speedy
    environment:
      ENV: ${ENV}
    ports:
      - '8080:3000'
    command: 'cd /var/speedy/app/speedy && bundle install && /bin/bash'
    tty: true
